# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventShiftSchedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventShiftSchedule.Event')),
            ],
        ),
        migrations.CreateModel(
            name='otpSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventShiftSchedule.OneTimePositions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='otpslot',
            unique_together=set([('user', 'otPosition')]),
        ),
        migrations.AlterUniqueTogether(
            name='onetimepositions',
            unique_together=set([('time', 'event')]),
        ),
    ]
