# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date',
            field=models.DateField(default=datetime.date(2016, 10, 14)),
        ),
        migrations.AlterField(
            model_name='time',
            name='beginning',
            field=models.TimeField(),
        ),
    ]
