# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0002_auto_20160822_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(),
        ),
    ]
