# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventShiftSchedule', '0002_auto_20160927_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
