# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventShiftSchedule', '0002_auto_20160927_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OneTimePositions',
            new_name='OneTimePosition',
        ),
    ]
