# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0002_shiftscheduleslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftscheduleslot',
            name='time',
            field=models.TimeField(),
        ),
    ]
