# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventShiftSchedule', '0003_auto_20160927_0802'),
        ('EventShiftSchedule', '0003_auto_20160927_1952'),
    ]

    operations = [
    ]
