# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0003_position_pref_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='time',
            name='date',
        ),
    ]
