# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventShiftSchedule', '0004_merge_20160928_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
