# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartyShiftSchedule', '0004_auto_20160822_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('time', 'user')]),
        ),
    ]
