# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0005_auto_20160826_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='party',
        ),
    ]
