# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0006_remove_slot_party'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Party',
            new_name='Event',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='party',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='party',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.FloatField(blank=True, default=2),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('name', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together=set([('beginning', 'duration', 'event')]),
        ),
    ]
