# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyShiftSchedule', '0007_auto_20160901_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='alt_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
